apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-docker
  name: demo-docker
spec:
  type: LoadBalancer
  selector:
    app: demo-docker
  ports:
    - name: tomcat
      port: 8080
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-docker
  name: demo-docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-docker
    spec:
      containers:
      - name: demo-docker
        image: jaimeperera/demo-docker:v1
        env:
        - name: TZ
          value: "Europe/Madrid"
        ports:
        - containerPort: 8080
          name: tomcat
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: tomcat
          initialDelaySeconds: 30
