apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-redis 
  name: my-redis
spec:
  type: LoadBalancer
  selector:
    app: my-redis
  ports:
    - name: redis
      port: 6379
      nodePort: 30379
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: my-redis
  name: my-redis

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - name: my-redis
        image: redis:3
        resources:
          requests:
            memory: "0.5Gi"
          limits:
            memory: "0.75Gi"
        env:
        - name: TZ
          value: "Europe/Madrid"
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
      - name: redis-storage
        hostPath:
          path: /data/redis-storage
