apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        app: my-redis 
      name: my-redis
    apiVersion: v1
    kind: Service
    spec:
      type: NodePort
      selector:
        app: my-redis
      ports:
        - name: redis
          port: 6379
          nodePort: 30379
          protocol: TCP
  - metadata:
      labels:
        app: my-redis
      name: my-redis
    apiVersion: v1
    kind: Deployment
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: my-redis
        spec:
          containers:
          - name: my-redis
            image: redis:3
            resources:
              requests:
                memory: "1Gi"
              limits:
                memory: "4Gi"
            env:
            - name: TZ
              value: "Europe/Madrid"
            ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
            livenessProbe:
              tcpSocket:
                port: redis
              initialDelaySeconds: 30
            volumeMounts:
            - mountPath: /data
              name: redis-storage
          volumes:
          - name: redis-storage
            hostPath:
              path: /data/redis-storage
