apiVersion: v1
kind: List
items:
  - metadata:
      name: demo-docker
    apiVersion: v1
    kind: Service
    spec:
      type: NodePort
      selector:
        app: demo-docker
      ports:
      - name: tomcat-port
        port: 8080
        targetPort: 8080
        nodePort: 32000
  - metadata:
      name: demo-docker
    apiVersion: extensions/v1beta1
    kind: Deployment
    spec:
      replicas: 1
      template:
        metadata:
          name: demo-docker
          labels:
            app: demo-docker
        spec:
          containers:
          - name: demo-docker
            image: demo-docker:v1
            imagePullPolicy: IfNotPresent 
            ports:
            - containerPort: 8080
            readinessProbe:
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 8080
              timeoutSeconds: 1
